### ISSUE TITLE
Scrolling doesn't work with mouse

### ISSUE THREAD

**Issue by milanvarady** [edudnyk/SolidScroll#4]
Scrolling doesn't work with a mouse wheel. I tried a vertical `SolidScrollView` and `PagingView` but it didn't work. I tried with a different mouse with the provided demo app, but no luck. Everything works fine with a trackpad, though. Do you know why is this happening?

**Comment by edudnyk** [comment]
I have no clue, this repository contains type aliases to hidden types of SwiftUI provided by Apple, not the implementation of them. Feel free to request Technical Support Incident in your Apple Developer Program and talk to Apple engineers about your question directly.
